name: RAW Consulting
favicon: null
layout_spectrum: 0.49856
typography_spectrum: 0.28499
title: Research At Work Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff8b'
    - '#000085'
    - '#7f7f88'
    - '#cfcf90'
    - '#3f3f86'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
