name: RAW Consulting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36436
title: Research At Work Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff8b'
    - '#000085'
    - '#7f7f88'
    - '#cfcf90'
    - '#3f3f86'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
