name: RAW Consulting
favicon: null
layout_spectrum: 0.4899
typography_spectrum: 0.28499
title: Research At Work Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5790d5'
    - '#1a1414'
    - '#5a563d'
    - '#b37357'
    - '#ecb783'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
